#ifndef _INALL_H_
#define _INALL_H_

#define DEBUG_VALUE_RELEASE 1
#define DEBUG_VALUE_DEBUG 100

#ifdef MAKE_DEBUG
#define DEBUG_VALUE DEBUG_VALUE_DEBUG
#else
#define DEBUG_VALUE DEBUG_VALUE_RELEASE
#endif

#define DEBUG_PRINT_FATFS DEBUG_VALUE
#define DEBUG_PRINT_FATFS_BOOTSEC 
#define DEBUG_PRINT_PART DEBUG_VALUE
#define DEBUG_PRINT_BDFILE DEBUG_VALUE
#define DEBUG_PRINT_BDHDD DEBUG_VALUE

#endif

